fixed_joints:
  - 0.0
  - -1.92
  - -0.39460
  - 0.0
  - 1.51
  - -0.00435
gripper_init:
  - 0.0
end_effector_index:
  - 7
rest_position:
  - 0.0
  - -1.92
  - -0.39460
  - 0.0
  - 1.51
  - -0.00435
urdf:
  - "assets/xarm_arm/xarm6_robot.urdf"

impedance_controller_cfg: ""
position_controller_cfg: ""